#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu
    username: Administrator
    password: "$6$HNZIhPAK3EaiTO80$DXDQGs7FMk6tLNa4BoN3sPcGZ6KZiutaH2iJ0tIUy834DCKcqENeu4UnXNFvBK0y9IQm6hxNpB6c3DJfV2NUi1"
  storage:
    layout:
      name: none
  packages:
    - vim
    - net-tools
    - wget
    - npm
    - samba
    - openjdk-8-jdk
    - openssh-client
    - openssh-server
